// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Menu struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	ShopName     string    `json:"shop_name"`
	ProductID    uuid.UUID `json:"product_id"`
	ProductName  string    `json:"product_name"`
	ProductPrice string    `json:"product_price"`
	Catalog      string    `json:"catalog"`
	Description  string    `json:"description"`
	CreatedAt    time.Time `json:"created_at"`
}

type Order struct {
	ID           uuid.UUID `json:"id"`
	ShopName     string    `json:"shop_name"`
	OrderID      uuid.UUID `json:"order_id"`
	OrderDay     string    `json:"order_day"`
	ProductName  string    `json:"product_name"`
	ProductPrice string    `json:"product_price"`
	Amount       int32     `json:"amount"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
}

type Product struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Name        string    `json:"name"`
	Price       string    `json:"price"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type User struct {
	ID             uuid.UUID `json:"id"`
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
}
